### ISSUE TITLE
Add DSA Algorithms only in Java 

### ISSUE THREAD

**Issue by AkashMarkad** [AkashMarkad/Hacktoberfest-2022#1]

**Comment by abhibarkade111** [comment]
Hey Can i Contribute to your repository.

**Comment by AvinashChourasia** [comment]
Hi, Can you assign this task to me. I want to add codes of some good problems of linked list, stack & queue.

**Comment by AvinashChourasia** [comment]
Under hacktoberfest label

**Comment by AkashMarkad** [comment]
Hey AvinashChourasia for contribution in my repository please see the readme.md file then you will get idea about how to contribute in my repository.
